CREATE TABLE Room (
    Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Name VARCHAR(20) NOT NULL,
    Windows INT NOT NULL,
    Doors INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Device(
	Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Name VARCHAR(20) NOT NULL,
	CreatedOn DATETIME NOT NULL,
	IsActive BOOLEAN NOT NULL,
	DeviceTypeId INT NOT NULL,
	RoomId INT NOT NULL,
	ActionId INT NOT NULL,
	FOREIGN KEY (DeviceTypeId) REFERENCES DeviceType(Id),
	FOREIGN KEY (RoomId) REFERENCES Room(Id),
	FOREIGN KEY (ActionId) REFERENCES Action(Id)
);
